### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by frnz65** [ORCID-EU-Labs/orcid-js#2]
Hello,

I have tried both examples. With one I get the message 
"My works:
Loading 0000-0002-1061-0510"   and then nothing.

With the other I get "Building BibTeX, please wait..." and then nothing.

Francesco

**Comment by misilot** [comment]
Try using the changes in PR #7. It should fix your issue.

**Comment by TomDemeranville** [comment]
fixed and merged
