### ISSUE TITLE
Orcid.js seem broken

### ISSUE THREAD

**Issue by ulli-steiner** [ORCID-EU-Labs/orcid-js#5]
It seems that there is an issue with orcid.js. It fails at the following routine:

	client.apis["Public API v2.0_rc4"].viewActivities({orcid:orcidID}, function(data) {
			if (data && data.obj && data.obj.works)
				console.log(data.obj.works.group.length + " works found");
			var simpleWorks = orcid.activitiesToSimpleWorks(data);
			if (oneByOne)
				orcid.fetchCiteprocJSONForSimpleWorksOneByOne(simpleWorks,resolveCiteproc);					
			else
				orcid.fetchCiteprocJSONForSimpleWorks(simpleWorks,resolveCiteproc);					
	});			

With the message:

Uncaught TypeError: Cannot read property 'viewActivities' of undefined

**Comment by ulli-steiner** [comment]
It seems that there is an issue with orcid.js. It fails at the following routine:

		client.apis["Public API v2.0_rc4"].viewActivities({orcid:orcidID}, function(data) {
				if (data && data.obj && data.obj.works)
					console.log(data.obj.works.group.length + " works found");
				var simpleWorks = orcid.activitiesToSimpleWorks(data);
				if (oneByOne)
					orcid.fetchCiteprocJSONForSimpleWorksOneByOne(simpleWorks,resolveCiteproc);					
				else
					orcid.fetchCiteprocJSONForSimpleWorks(simpleWorks,resolveCiteproc);					
		});			



With the message:

Uncaught TypeError: Cannot read property 'viewActivities' of undefined

**Comment by misilot** [comment]
PR #7 should fix this issue. If you remove "_rc4" from the file and use the 2.0 API it should work as expected.

**Comment by TomDemeranville** [comment]
fixed and merged
